spring.application.name=dokvaktmester
spring.main.banner-mode=off
spring.shell.history.enabled=false
spring.shell.command.history.enabled=false
spring.shell.command.script.enabled=false
spring.shell.command.version.enabled=false
spring.shell.interactive.enabled=false