name: Endre distribusjonsinfo journalpost (dev)
run-name: Endre distribusjonsinfo journalpost. journalpostId=${{ github.event.inputs.journalpostId }} av @${{ github.actor }} (dev)

on:
  workflow_dispatch:
    inputs:
      journalpostId:
        description: "journalpostId som skal få endret distribusjonsinfo: utsendingskanal, og settes til ekspedert"
        required: true
        type: string
      utsendingskanal:
        description: "Utsendingskanal som det skal endres til (default er lokal print)"
        required: false
        type: string

jobs:
  deploy:
    name: Endre distribusjonsinfo journalpost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator-endre-distribusjonsinfo-journalpost.yaml
          VARS: .nais/q2-config.json
          VAR: IMAGE=europe-north1-docker.pkg.dev/nais-management-233d/teamdokumenthandtering/dokvaktmester:latest,COMMAND=endre-distribusjonsinfo-journalpost,ARGUMENT1=--journalpostId ${{ github.event.inputs.journalpostId }},ARGUMENT2=--utsendingskanal ${{ github.event.inputs.utsendingskanal }}
          PRINT_PAYLOAD: true
