name: Sett avbrutt brev til redigerbart (dev)

on:
  workflow_dispatch:
    inputs:
      journalpostId:
        description: "JournalpostId til brevet som skal settes redigerbart"
        required: true
        type: number

jobs:
  deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator.yaml
          VARS: .nais/q4-config.json
          VAR: IMAGE=europe-north1-docker.pkg.dev/nais-management-233d/teamdokumenthandtering/dokvaktmester:latest,COMMAND="sett-avbrutt-brev-redigerbart ${{ github.event.inputs.journalpostId }}"
          PRINT_PAYLOAD: true