name: Sett distribusjon feilet (dev)
run-name: Sett distribusjon feilet. distribusjonId=${{ github.event.inputs.distribusjonId }} av @${{ github.actor }} (dev)

on:
  workflow_dispatch:
    inputs:
      distribusjonId:
        description: "DistribusjonId til distribusjonen som skal settes til FEILET"
        required: true
        type: string
      mmaSak:
        description: "MMA-sak som er årsak til endringen (settes som endretAv)"
        required: true
        type: string

jobs:
  deploy:
    name: Sett distribusjon feilet
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator-sett-distribusjon-feilet.yaml
          VARS: .nais/q4-config.json
          VAR: IMAGE=europe-north1-docker.pkg.dev/nais-management-233d/teamdokumenthandtering/dokvaktmester:latest,COMMAND=sett-distribusjon-feilet,ARGUMENT1=--distribusjonId ${{ github.event.inputs.distribusjonId }},ARGUMENT2=--mmaSak ${{ github.event.inputs.mmaSak }}
          PRINT_PAYLOAD: true
